version: '3.7'
services:
  prod:
    hostname: hello-go-prod
    restart: unless-stopped
    build:
        context: ..
        dockerfile: Dockerfile
        target: base
    ports:
     - "8000:8000"
    volumes:
        - ..:/go/src/github.com/tatsuki5820iso/HelloGo
    working_dir: /go/src/github.com/tatsuki5820iso/HelloGo
    command: bash -c "export GO111MODULE=on && go mod download && go build -o ./main main.go && ./main"
  dev:
    hostname: hello-go-dev
    restart: unless-stopped
    build:
        context: ..
        dockerfile: Dockerfile
        target: dev
    ports:
     - "8001:8000"
    volumes:
        - ..:/go/src/github.com/tatsuki5820iso/HelloGo
    working_dir: /go/src/github.com/tatsuki5820iso/HelloGo
    command: bash -c "export GO111MODULE=on && go mod download && cd docker &&  make serve"
